python main.py \
  --data_path ./dataset/2a \
  --subject 0 \
  --dataset BCI2a \
  --model multiband_mamba \
  --mamba_dim 96 \
  --batch_size 32 \
  --dropout 0.5 \
  --epochs 2000 \
  --lr 1e-3 \
  --weight_decay 0.01 \
  --mixup \
  --mixup_alpha 0.4 \
  --grad_clip 1.0 \
  --patience 500 \
  --augment \
  --augment_factor 3 \
  --scheduler cosine \
  --label_smoothing 0.15 \
  --fre_filter \
  --optimizer adamw \
  --save_model \
  --plot_curves \
  --plot_cm \
  --save_dir ./experiment_results/$(date +%Y%m%d_%H%M%S)
