python main.py \
  --data_path ./dataset/2a \
  --subject 0 \
  --dataset BCI2a \
  --model multiband_mamba \
  --mamba_dim 96 \
  --batch_size 32 \
  --dropout 0.4 \
  --epochs 1000 \
  --lr 1e-3 \
  --weight_decay 0.001 \
  --mixup \
  --mixup_alpha 0.4 \
  --grad_clip 0.3 \
  --patience 200 \
  --augment \
  --augment_factor 4 \
  --save_model \
  --plot_curves \
  --plot_cm \
  --save_dir ./experiment_results/$(date +%Y%m%d_%H%M%S)
